# Generated by Django 6.0.7 on 2026-09-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_admissionapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='previous_qualification',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='program',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='board_roll_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='course',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_cnic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='heard_about_us',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='obtained_marks',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='passing_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='student_cnic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='student_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='total_marks',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
