# Generated by Django 6.0.7 on 2026-09-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_remove_admissionapplication_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
