# Generated by Django 6.0.7 on 2026-09-15 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_admissionapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='guardian_cnic',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_cnic',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_contact',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
